#!/usr/bin/env python

from operator import itemgetter
import sys

current_word = None
happy_count = 0
sad_count = 0
word = None

# input comes from STDIN
for line in sys.stdin:
    # remove leading and trailing whitespace
    line = line.strip()

    # parse the input we got from mapper.py
    word, count = line.split('\t', 1)

    # convert count (currently a string) to int
    try:
        count = int(count)
    except ValueError:
        # count was not a number, so silently
        # ignore/discard this line
        continue

    # this IF-switch only works because Hadoop sorts map output
    # by key (here: word) before it is passed to the reducer
    if word in [":)",":^)",":D","happy","joy","love","easy","hope","fun","delight","excite","pleasure","affect","friends","friendly","hope","pride","satisfy","satisfact","trust","calm","peace","content","relax","relief","interesting","fond","adore","glee","glad","ecstasy","triumph","eager","anticipat","optimis","awe","kind","comfortable","cosy","eager","fun","awesome","amazing","jovial","good","nice","yay","warm","family","best","serene","blessed","cheerful","festive"]:
        happy_count = happy_count + 1
        print '%s\t%s\t%s' % (word, happy_count, sad_count)
    elif word in [":(",":^(",":/","bored","sad","bored","lone","anger","angry","annoy","disgust","irritat","embarrass","fear","helpless","negative","worry","anxious","envy","frustrat","guilt","shame","bored","despair","disappoint","hurt","sad","stress","shock","tension","hate","sorry","rage","torment","anguish","horror","gloom","unhappy","pessimis","torment","wrath","revenge","fury","grief","sorrow","woe","misery","miserable","displeasure","fright","uneas","dread","pissed","haggered","paralyzed","scared","slump","terrible","worthless","shitty","down","rotten","cranky","negative","moody"]:
        sad_count = sad_count + 1
        print '%s\t%s\t%s' % (word, happy_count, sad_count)
    else:
        if current_word:
            # write result to STDOUT
            print '%s\t%s\t%s' % (current_word, happy_count, sad_count)
        current_word = word

# do not forget to output the last word if needed!
if current_word == word:
    print '%s\t%s\t%s' % (current_word, happy_count, sad_count)
